// 08_viejs/src/components/NovaPoshtaCity.vue
<template>
  <div v-if="error">Error</div>
  <div v-else-if="isLoading">Loading</div>
  <ul v-else id="areaList">
    <h3>Cities:</h3>
    <li v-for="item in items" :key="item.Ref" class="text-start">
      {{ item.DescriptionRu }}
    </li>
  </ul>
</template>

<script>
export default {
  name: "NovaPoshtaCity",
  data: () => {
    return {
      items: [],
      isLoading: false,
      error: null
    }
  },
  beforeMount: function () {
    this.loadAreas();
  },
  methods: {
    loadAreas() {
      fetch(
          "https://api.novaposhta.ua/v2.0/json/",
          {
            method: 'POST',
            headers: {'Content-Type': 'application/json'},
            body: JSON.stringify({
              "apiKey": "3c81d19dc6c4375bc278f4c329fb03cb",
              "modelName": "Address",
              "calledMethod": "getCities",
              "methodProperties": {},
            })
          }
      )
          .then(response => {
            if (response.status !== 200) {
              console.log(response.status);
              console.log(response.statusText);
              this.$data.error = response.status;
            }
            return response.json();
          })
          .then(json => {
            if (json['success']) {
              this.$data.items = json["data"];
            } else {
              console.log(json['errors']);
              console.log(json['warnings']);
              this.$data.error = json['errors'];
            }
          })
          .catch(err => {
            console.log(err);
            this.$data.error = err;
          })
    }
  }
}
</script>

<style scoped>

</style>

// Angular/src/app/MyComponent/nova-poshta-city/nova-poshta-city/nova-poshta-city.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-nova-poshta-city',
  templateUrl: './nova-poshta-city.component.html',
  styleUrls: ['./nova-poshta-city.component.css']
})
export class NovaPoshtaCityComponent implements OnInit {

  itemsCity = [];

  constructor() { }

  ngOnInit(): void {
    fetch(
      "https://api.novaposhta.ua/v2.0/json/",
      {
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify({
          "apiKey": "3c81d19dc6c4375bc278f4c329fb03cb",
          "modelName": "Address",
          "calledMethod": "getCities",
          "methodProperties": {
          },
        })
      }
    )
      .then(response => {
        if (response.status !== 200) {
          console.log(response.status);
          console.log(response.statusText);
          console.log("error");
        }
        return response.json();
      })
      .then(json => {
        if (!json['success']) {
          console.log("Error: ");
          return;
        }
        console.log(json.data);
        this.itemsCity = json.data;
      })
      .catch(err => {
        console.log(err);
        console.log(err);
      })
  }

}

<h3>Cities:</h3>
<ul id="areaList">
  <li *ngFor="let item of itemsCity">
    {{ item['DescriptionRu'] }}
  </li>
</ul>
